apiVersion: v1
kind: Service
metadata:
  name: {{ include "kevin-agent.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kevin-agent.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kevin-agent.name" . }}-backend
    app.kubernetes.io/component: backend
